import { getStoredLang, type Lang } from './i18n'

const english: Record<string, string> = {
  "Mục đồng bộ đã thay đổi. Vui lòng thử lại.": "This sync entry changed. Please try again.",
  "Bản trên máy vừa thay đổi. Vui lòng xem lại xung đột.": "The local copy just changed. Please review the conflict again.",
  "Không tìm thấy thẻ ôn tập của ghi chú này.": "This note no longer has a scheduled review card.",
  "Tiểu sử": "Biography",
  "Hư cấu": "Fiction",
  "Lịch sử": "History",
  "Trinh thám": "Mystery",
  "Lãng mạn": "Romance",
  "Khoa học viễn tưởng": "Science fiction",
  "Tài liệu": "Document",
  "Đang ngoại tuyến. Thay đổi của bạn được giữ trên trình duyệt.": "You are offline. Your changes stay in this browser.",
  "Đã đồng bộ với tài khoản của bạn.": "Your account is up to date.",
  "Phiên đăng nhập đã hết hạn. Dữ liệu trên trình duyệt vẫn được giữ riêng.": "Your session expired. Your browser data remains separate and saved.",
  "Đã đăng xuất. Dữ liệu tài khoản được giữ riêng và không bị xóa.": "Signed out. Your account data stays separate and has not been deleted.",
  "Hỗ trợ EPUB, PDF, CBZ, TXT, Markdown, HTML, DOCX, JPG, PNG và WebP.": "Supported formats: EPUB, PDF, CBZ, TXT, Markdown, HTML, DOCX, JPG, PNG and WebP.",
  "Tệp trống hoặc vượt giới hạn 250 MB.": "The file is empty or exceeds the 250 MB limit.",
  "Đang tính mã băm và chuẩn bị tài liệu...": "Preparing your document…",
  "Tài liệu của bạn": "Your document",
  "Đang tải tệp lên Cloud...": "Uploading your file…",
  "Đã thêm và đồng bộ tài liệu riêng lên Cloud thành công.": "Your private document was added and synced to the cloud.",
  "Đã thêm tài liệu vào trình duyệt này. Đăng nhập để tự động sao lưu lên Cloud.": "Document added to this browser. Sign in to upload it to your private cloud.",
  "Tệp sách không có nội dung.": "The book file is empty.",
  "Đã bỏ dấu trang tại vị trí này.": "Bookmark removed.",
  "Đã thêm dấu trang.": "Bookmark added.",
  "Ghi chú tại vị trí đọc": "Note at the reading position",
  "Đã lưu ghi chú.": "Note saved.",
  "Tài liệu không tên": "Untitled document",
  "Đã xuất toàn bộ ghi chú ra tệp Markdown (.md)!": "Your notes were exported to Markdown (.md).",
  "Chưa có trích dẫn hoặc ghi chú nào trong mục Điều đáng nhớ để ôn tập.": "Save a highlight or note in Reading Memory before reviewing.",
  "Đã xóa tài liệu.": "Document deleted.",
  "Đóng menu": "Close menu",
  "Điều hướng": "Navigation",
  "Menu chính": "Main menu",
  "Tài khoản": "Account",
  "Mở menu": "Open menu",
  "Đóng thông báo": "Dismiss notification",
  "Bộ lọc tủ sách": "Library filters",
  "Tìm sách": "Search books",
  "Lọc thể loại": "Filter by category",
  "Sắp xếp sách": "Sort books",
  "Lọc theo thẻ hoặc bộ sưu tập": "Filter by tag or collection",
  "Tìm ghi chú": "Search notes",
  "Mục lục sách": "Table of contents",
  "MỤC LỤC SÁCH": "TABLE OF CONTENTS",
  "Đóng mục lục": "Close table of contents",
  "Tài liệu không có cấu trúc mục lục sẵn.": "This document has no table of contents.",
  "Tùy chỉnh đọc": "Reading settings",
  "Đóng": "Close",
  "Cỡ chữ": "Font size",
  "Kiểu chữ": "Typeface",
  "Literata · Sách": "Literata · Books",
  "Atkinson · Dễ đọc": "Atkinson · Accessible",
  "Đơn cách": "Monospace",
  "Căn lề": "Alignment",
  "Trái": "Left",
  "Căn đều 2 bên": "Justified",
  "Khoảng cách dòng": "Line spacing",
  "Gọn (1.4)": "Compact (1.4)",
  "Vừa (1.65)": "Standard (1.65)",
  "Thoáng (1.9)": "Relaxed (1.9)",
  "Độ rộng trang": "Reading width",
  "Gọn": "Narrow",
  "Tiêu chuẩn": "Standard",
  "Rộng": "Wide",
  "Màu nền": "Background",
  "Giấy sáng": "Paper light",
  "Vàng dịu": "Sepia",
  "Ban đêm": "Night",
  "Lưu điều đáng nhớ": "Save something memorable",
  "Màu highlight:": "Highlight color:",
  "Ghi chú của bạn": "Your note",
  "Điều gì khiến bạn muốn giữ đoạn này?": "What would you like to remember about this passage?",
  "Hủy": "Cancel",
  "Đang lưu…": "Saving…",
  "Lưu ghi chú": "Save note",
  "Lưu đoạn trích": "Save highlight",
  "Ôn tập ghi chú Flashcards": "Review note flashcards",
  "FLASHCARD REVIEW · THẺ": "FLASHCARD REVIEW · CARD",
  "đã thuộc": "remembered",
  "Ghi nhớ quan trọng": "Something to remember",
  "💡 Bấm thẻ để lật xem ghi chú suy ngẫm": "💡 Click the card to see your note",
  "GHI CHÚ & SUY NGẪM": "NOTES & REFLECTIONS",
  "Nội dung ghi chú của bạn:": "Your note:",
  "Không có ghi chú riêng; hãy ghi nhớ lại đoạn trích trên.": "No extra note; recall the highlighted passage.",
  "Đánh giá khả năng ghi nhớ bên dưới:": "Rate how well you remember below:",
  "Xem lại mặt trước": "Show front",
  "Lật thẻ xem ghi chú": "Flip to see note",
  "🔴 Cần ôn lại": "🔴 Review again",
  "🟢 Đã nhớ rõ": "🟢 Remembered",
  "Hoàn thành phiên ôn tập!": "Review complete!",
  "Tuyệt vời! Bạn đã xem lại toàn bộ các thẻ ghi chú trong phiên này.": "You have reviewed all the cards in this session.",
  "✓ Đã nhớ:": "✓ Remembered:",
  "thẻ": "cards",
  "↺ Ôn lại:": "↺ Reviewed again:",
  "lần": "times",
  "Ôn tập lại": "Review again",
  "Hoàn tất": "Done",
  "Đọc ẩn công sở": "Stealth reading",
  "Chương": "Chapter",
  "Trang": "Page",
  "Mục": "Section",
  "Phần": "Section",
  "Màu": "Color",
  "Mở": "Open",
  "Tác giả": "Author",
  "Ghi chú": "Note",
  "Vị trí": "Location",
  "Không mở được EPUB này. Tệp có thể bị hỏng hoặc không đúng định dạng.": "Unable to open this EPUB. The file may be damaged or invalid.",
  "Nội dung EPUB": "EPUB content",
  "Không mở được PDF này. Tệp có thể bị hỏng hoặc được bảo vệ.": "Unable to open this PDF. The file may be damaged or protected.",
  "Không hiển thị được trang PDF này.": "Unable to display this PDF page.",
  "Không tìm thấy tệp ảnh nào trong tệp truyện tranh CBZ.": "No images were found in this CBZ comic.",
  "Không mở được tệp CBZ.": "Unable to open this CBZ.",
  "Đang giải nén truyện tranh…": "Extracting comic pages…",
  "Trang đơn": "Single page",
  "Cuộn dọc (Webtoon)": "Vertical scrolling (Webtoon)",
  "Không hiển thị được ảnh này. Tệp có thể bị hỏng hoặc không đúng định dạng.": "Unable to display this image. The file may be damaged or invalid.",
  "Không đọc được nội dung tài liệu này.": "Unable to read this document.",
  "Không tìm thấy ghi chú trong tài khoản này.": "This note is not available in your account.",
  "Ghi chú không hợp lệ.": "This note is invalid.",
  "Phiên đăng nhập đã hết hạn. Đăng nhập lại để đồng bộ.": "Your session expired. Sign in again to sync.",
  "Không hoàn tất được thao tác. Vui lòng thử lại.": "Unable to complete this action. Please try again.",
  "Máy chủ phản hồi quá lâu. Vui lòng thử lại.": "The server took too long to respond. Please try again.",
  "Không kết nối được máy chủ. Kiểm tra mạng rồi thử lại.": "Unable to connect to the server. Check your connection and try again.",
  "Không kết nối được máy chủ khi tải tệp lên. Kiểm tra mạng rồi thử lại.": "Unable to upload the file. Check your connection and try again.",
  "Thiếu tệp gốc để đồng bộ tài liệu đã khôi phục. Hãy nhập lại tệp.": "The restored document’s original file is missing. Import the file again.",
  "Máy chủ chưa xác nhận thao tác đồng bộ.": "The server has not confirmed the sync operation.",
  "Có quá nhiều thay đổi để tải một lần. Vui lòng đồng bộ lại.": "There are more changes to download. Please sync again.",
  "Email hoặc mật khẩu không đúng": "Incorrect email or password.",
  "Email không hợp lệ": "Enter a valid email address.",
  "Mật khẩu phải có ít nhất 8 ký tự": "Your password must contain at least 8 characters.",
  "Thao tác quá nhiều lần. Vui lòng thử lại sau.": "Too many attempts. Please try again later.",
  "Vui lòng đăng nhập lại": "Please sign in again.",
  "Phiên đăng nhập đã hết hạn": "Your session expired.",
  "Tài khoản không hoạt động": "This account is inactive.",
  "Vui lòng xác minh email trước": "Please verify your email first.",
  "Dịch vụ email chưa được cấu hình. Vui lòng dùng Google hoặc thử lại sau.": "Email is currently unavailable. Use Google sign-in or try again later.",
  "Chưa gửi được email. Vui lòng thử lại sau.": "Unable to send the email. Please try again later.",
  "Email đã được sử dụng. Vui lòng đăng nhập hoặc đặt lại mật khẩu.": "This email is already registered. Sign in or reset your password.",
  "Email đã được sử dụng": "This email is already registered.",
  "Đăng nhập Google không hợp lệ": "Google sign-in could not be verified.",
  "Google chưa xác minh email": "Your Google email has not been verified.",
  "Hãy xác minh tài khoản email trước khi liên kết Google": "Verify your email account before linking Google.",
  "Liên kết hết hạn hoặc đã được sử dụng": "This link has expired or has already been used.",
  "Bỏ qua phần giới thiệu": "Skip introduction",
  "Bỏ qua": "Skip",
  "Nhấp vào bìa sách để mở": "Click the book cover to open",
  "TẬP I • TIỂU LUẬN": "VOLUME I • ESSAYS",
  "ơi đây, từng con chữ không còn là dữ liệu khô khan mà trở thành những bậc thang dẫn vào chiều sâu của tư duy. Trong một thế giới tràn ngập tiếng ồn, sự tĩnh lặng của trang giấy chính là sự xa xỉ quý giá nhất.": "ere, words become steps toward deeper thought. In a noisy world, the stillness of a page is a precious luxury.",
  "Khi lật từng trang sách, bạn không chỉ đọc một câu chuyện, mà đang tìm lại chính mình trong từng khoảnh khắc chiêm nghiệm thuần khiết.": "With every page, a story becomes a moment to reflect and rediscover yourself.",
  "CHƯƠNG II": "CHAPTER II",
  "GHI CHÚ": "NOTES",
  "CHƯƠNG III": "CHAPTER III",
  "PHỤ LỤC": "APPENDIX",
  "CHƯƠNG IV": "CHAPTER IV",
  "TƯ DUY": "THOUGHT",
  "CHƯƠNG V": "CHAPTER V",
  "TRIẾT HỌC": "PHILOSOPHY",
  "CHƯƠNG VI": "CHAPTER VI",
  "KẾT NỐI": "CONNECTION",
  "CHƯƠNG VII": "CHAPTER VII",
  "VĨ THANH": "EPILOGUE",
  "\"Trang sách mở rộng biên độ của tâm thức...\"": "\"Pages expand the horizons of thought…\"",
  "\"Dòng thời gian trôi qua nhẹ nhàng như dòng suối nhỏ...\"": "\"Time flows gently like a stream…\"",
  "\"Mỗi con đường là một cuộc phiêu lưu bất tận...\"": "\"Every path is an endless adventure…\"",
  "\"Ánh sáng của tri thức xóa nhòa bóng tối mơ hồ...\"": "\"Knowledge brings clarity to the unknown…\"",
  "\"Sự hiểu biết đem lại nguồn sức mạnh tĩnh tại...\"": "\"Understanding brings quiet strength…\"",
  "\"Lắng nghe những rung động tinh tế nhất...\"": "\"Listen to the smallest echoes…\"",
  "\"Vượt qua những giới hạn định kiến thông thường...\"": "\"Look beyond familiar assumptions…\"",
  "\"Khát vọng vươn tới chân trời tự do...\"": "\"Reach toward an open horizon…\"",
  "\"Hội ngộ những tâm hồn đồng điệu...\"": "\"Meet minds that share your curiosity…\"",
  "\"Chạm vào tinh hoa của nhân loại...\"": "\"Explore the richness of human thought…\"",
  "\"Hành trình vạn dặm khởi đầu từ một trang sách...\"": "\"A long journey can begin with a single page…\"",
  "\"Vòng tuần hoàn không bao giờ ngưng nghỉ...\"": "\"The journey of learning never ends…\""
}

export function translate(text: string, lang: Lang = getStoredLang()): string {
  return lang === 'en' ? english[text] || text : text
}

export function localizeErrorMessage(text: string, lang: Lang = getStoredLang()): string {
  const message = translate(text, lang)
  return lang === 'en' && /[À-ỹ]/u.test(message) && message === text ? 'Unable to complete this action. Please try again.' : message
}
